# Generated by Django 5.2.1 on 2025-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_services', '0002_reporter_articles_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='publisher',
            field=models.ManyToManyField(to='blog_services.publisher'),
        ),
    ]
